name: tz_datetime_web_example
description: "Demonstrates how to use the tz_datetime plugin."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

resolution: workspace

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

  tz_datetime: any
  tz_datetime_web: any

dev_dependencies: 
  flutter_lints: ^6.0.0
