name: tz_datetime_web
description: "Time zoned datetime for web."
version: 1.0.0
repository: https://github.com/llfbandit/tz_datetime

resolution: workspace

environment:
  sdk: ^3.8.1
  flutter: ">=3.32.1"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  web: ^1.0.0

  tz_datetime_platform_interface: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: TzDatetimeWeb
        fileName: tz_datetime_web.dart
