name: tz_datetime_darwin
description: "Time zoned datetime for tz_datetime package. iOS/macOS implementation."
version: 1.0.0
repository: https://github.com/llfbandit/tz_datetime/tree/master/tz_datetime_darwin

resolution: workspace

environment:
  sdk: ^3.8.1
  flutter: ">=3.32.1"

dependencies:
  flutter:
    sdk: flutter

  tz_datetime_platform_interface: ^1.0.0

  objective_c: ^9.2.3
  ffi: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  ffigen: ^20.0.0

flutter:
  plugin:
    platforms:
      ios:
        dartPluginClass: TzDatetimeDarwin
        dartFileName: 'tz_datetime_darwin.dart'
      macos:
        dartPluginClass: TzDatetimeDarwin
        dartFileName: 'tz_datetime_darwin.dart'
