name: tz_datetime_android
description: "A new Flutter plugin project."
version: 1.0.0

resolution: workspace

environment:
  sdk: ^3.9.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  tz_datetime_platform_interface: ^1.0.0

  jni: ^0.15.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  jnigen: ^0.15.0

flutter:
  plugin:
    platforms:
      android:
        dartPluginClass: TzDatetimeAndroid
        dartFileName: 'tz_datetime_android.dart'
        ffiPlugin: true
