name: tz_datetime_windows
description: "Time zoned datetime for tz_datetime package. Windows implementation."
version: 1.0.0
repository: https://github.com/llfbandit/tz_datetime/tree/master/tz_datetime_windows

resolution: workspace

environment:
  sdk: ^3.8.1
  flutter: ">=3.32.1"

dependencies:
  flutter:
    sdk: flutter

  tz_datetime_platform_interface: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      windows:
        dartPluginClass: TzDatetimeWindows
        dartFileName: 'tz_datetime_windows.dart'
